### ISSUE TITLE
Complete TypeScript guidelines

### ISSUE THREAD

**Issue by mcmire** [MetaMask/contributor-docs#69] opened 2024-01-03 23:11 UTC
We've started a document which is intended to contain TypeScript guidelines, but it is severely lacking in content.

We should get to an MVP by adding the following guidelines:

- Use enums instead of union types
- Avoid type assertions, or explain their usage when necessary

**Comment by mcmire** [comment] 2024-01-03 23:38
Off the top of my head, here's a list of guidelines we could include:

- Don't use numeric enums
  - Numeric enums are misleading because it creates a reverse mapping from value to property name, making `Object.values` not do what you think it does
- Constrain generic types if necessary
  - It may not be enough just to have a type or a function take another type — you might have to constrain it if it's not allowed to be anything (e.g. `extends Json`)
- 💡 Use `Partial` to type the accumulating variable in `reduce`
- 💡 Use `Omit` to reduce requirements
  - If you want to reuse a type for, say, an argument to a function, but you only use part of that type, then you can use `Omit` to reduce that type to a subset. This makes it easier to test the function because you don't have to create a full version of the object that represents the original type.
- Use enums instead of union types
  - Inevitably you will want to refer to the values of a union type somewhere (perhaps as the argument to a function). You can of course just use a literal which represents a member of that union — but if you have an enum, then all of the values are special, and any time you use a value then anyone can see where that value comes from.
- Don't use `any`
  - `any` doesn't actually represent "any type"; if you declare a value as `any`, it tells TypeScript to disable typechecking for that value anywhere it appears.
  - `any` is dangerous because it infects all surrounding and downstream code. For instance, if you have a function that is declared to return `any` which actually returns an object, all properties of that object will be `any`.
  - Need to truly represent something as "any value"? Use `unknown` instead.
- Avoid type assertions, or explain why they are needed
  - Notable exceptions: `reduce`, iterating over the keys of an enum
- Avoid type annotations
  - Notable exceptions: `reduce` (?)
  - Need to create a data structure with specific values, but ensure that it's declared with a more abstract type? Create a function that takes an argument of the type you want, then use it to build the object. (Note: This will be solved in a future version of TypeScript with the `satisfies` keyword.)

There are also a couple of tickets we've created already:

- https://github.com/MetaMask/contributor-docs/issues/47
- https://github.com/MetaMask/contributor-docs/issues/57

**Comment by desi** [comment] 2024-01-04 16:33
To get to an MVP we are going to do the enum bullet, don't use any bullet and the type assertions bullet. We will come back to additional items later. Pointing based on this comment.

**Comment by MajorLift** [comment] 2024-01-09 03:17
Initial notes on `any` (will edit this comment to add new material):

## Avoiding `any`
- `unknown` is the universal supertype i.e. the widest possible type. 
	- If what's needed is a type that could be "anything," `unknown` should be used.
	- `any` doesn't provide a wide type. It's a compiler setting to disable type checking for the type it's assigned to, which compromises type safety by definition.
- If replacing `any` with `unknown` doesn't work, the typing very likely has underlying issues that *shouldn't be silenced*. 
- If `any` is used, and errors are introduced (or altered) by future changes to the code, 
	- the new or changed warnings will be suppressed,
	- and the code will **fail silently**. 
	- "dangerous because infects all surrounding and downstream code ..."
- If no good typing solution can be found, using forced type casting with the `as` keyword or even `as unknown as` is much preferable to using `any`:
	- At least we get working intellisense, autocomplete.
	- We also get an indication of the expected type as intended by the author.

- Function supertype (assignable to any function):
```ts
(...args: any[]) => any // bad
(...args: never[]) => unknown // good
```

## Acceptable usages of `any`
- Assigning new properties to an object or class at runtime:
```ts
(this as any)[key] = obj[key]
```
- Within generic constraints:
```ts
messenger extends RestrictedControllerMessenger<N, any, any, string, string>
```
	- In general, using `any` in this context is not harmful in the same way that it is in other contexts, as the `any` types are not directly assigned to any specific variable, and only function as constraints. 
	- That said, more detailed constraints don't hurt either.
- Catching errors: 
	- `catch` only accepts `any` and `unknown` as the error type .
	- Recommended: Use `unknown` with type guards like `isJsonRpcError` .
- Mocking for tests:
	- Recommended: Provide accurate typing through assertions wherever possible.

**Comment by MajorLift** [comment] 2024-01-25 15:23
Additional ideas (WIP): 

- Prefer the nullish coalescing operator `??`.
  - `??` guarantees that the left-hand operand is nullish but not falsy, which reduces cognitive overhead for reviewers.
  - Using `||` leads reviewers to assume that `??` was intentionally avoided, forcing them to consider cases where the left-hand operand is falsy. This should never happen if the left-hand operand is nullish but not falsy.

**Comment by MajorLift** [comment] 2024-01-26 19:15
I think there might be an opportunity here to look into static code analysis tools or code smell linters like sonarlint. 

For some cases we could potentially adopt linter rules instead of writing our own guidelines. Linter rules are easily enforceable, and they come with their own documentation we can point to.

These are the rule categories that might be of interest:
- https://rules.sonarsource.com/typescript/type/Code%20Smell/
- https://rules.sonarsource.com/typescript/quickfix/
- https://rules.sonarsource.com/typescript/type/Bug/

**Comment by MajorLift** [comment] 2024-02-29 16:57
@mcmire @desi Thoughts on converting this to an epic? I think we have enough items and content here that this would be better managed as a bunch of small PRs.

**Comment by MajorLift** [comment] 2024-03-07 07:51
WIP: This may or may not be appropriate to include in the guidelines.

### Type System Concepts

#### Assignee vs. Assigned

```typescript
// Assignment operation - LHS: 'Assignee', RHS: 'Assigned'
const assignee: Assignee = assigned;

// Function call - parameter: 'Assignee', argument: 'Assigned'
function example(param: Assignee) {}
example(assigned);

// Generic parameters with constraints
type ExampleGeneric<Param extends Assignee> = Param;
type ExampleType = GenericExample<Assigned>;

// Relationship - The 'Assigned' type is a subtype of the 'Assignee'
type IsTrue = Assigned extends Assignee ? true : false;
```

#### Widest Subtype vs. Narrowest Supertype

- The widest subtype represents the minimum structure and content that a given type must satisfy.
  - "Subtype" is a meaningless category without the qualifier "widest" e.g. `never` is a subtype of all types.
  - The widest subtype is a full instance of the given type.
  - A narrower subtype would no longer be considered the same type.
  - "Greatest lower bound" and "inf (_infimum_)" are analogous concepts.
- The narrowest supertype represents the maximum structure and content that a given type can contain while still exclusively being the same type.
  - "Supertype" is a meaningless category without the qualifier "narrowest" e.g. `unknown` is a supertype of all types.
  - The narrowest supertype encompasses all instances of the given type.
  - A wider supertype would begin to contain elements of other types.
  - "Least upper bound" and "sup (_supermum_)" are analogous concepts.

#### Definition vs. Constraint

- A type definition represents the exact structure and contents of a value or type, and is populated by literal expressions.
  - This is the assigned type in a type declaration or expression.
  - This is the widest subtype.
- A type constraint is a wider, abstract type that defines the properties and structure a type is required to satisfy in order to fit into a given category.
  - This is the assignee type in a type declaration or expression.
  - This is the narrowest supertype.

#### Subtyping shorthands

- Narrow `extends` Wide
- Assigned `extends` Assignee
- Subtype `extends` Supertype
- Subclass `extends` Superclass
- Member `extends` Union
- Intersection `extends` Member
- StrictlyDeepEqualTuple `extends` StrictlyDeepEqualTuple
- `(...args: Supertype) => void` extends `(...args: Subtype) => void` (contravariance)
- `never` `extends` Everything (`never` is assignable to everything)
- Everything `extends` `unknown` (everything is assignable to `unknown`)

**Comment by desi** [comment] 2024-03-07 16:17
@desi convert this to an epic. Once converted to an epic remove the estimate and create additional issues that represent the comments and statements above.

**Comment by mcmire** [comment] 2024-03-07 21:33
@MajorLift Your glossary seems like it could be quite helpful, even for people who think they are familiar with TypeScript. I too am not sure where it belongs exactly - perhaps another document, or maybe at the very bottom of the current document?

**Comment by MajorLift** [comment] 2024-03-07 22:56
It might make sense to have a dedicated doc for type concepts with explanations about some of the more complex types we use. I'll keep collecting material here until it reaches a critical mass.

**Comment by MajorLift** [comment] 2024-03-16 02:32
- Duplicate: https://github.com/MetaMask/contributor-docs/issues/4

**Comment by MajorLift** [comment] 2024-04-30 18:52
Closed by https://github.com/MetaMask/contributor-docs/pull/74, which, together with https://github.com/MetaMask/contributor-docs/pull/80, covers the initial topics listed in https://github.com/MetaMask/contributor-docs/issues/69#issuecomment-1876114356. 

The content suggested by later comments will be preserved here and included in future contributor-docs articles.

**Closed by MajorLift** 2024-04-30 18:52 UTC
Labels: team-shared-libraries
